language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install pytest pytest-cov
    - pip install mockito
    - pip install coveralls
    - pip install radon
    - pip install pep8
    - pip install pylint
# command to run tests
script:
    - py.test --cov . --cov-report term-missing

after_success:
    - radon cc src/ , test/
    - radon mi src/ , test/
    - radon raw src/ , test/
    - coveralls
    - pep8 src/ , test/
    - pylint src/ , test
    
notifications:
    emails:
        - n_3_n3@hotmail.com
        - ezequielra1@gmail.com
    on_failure: always
